# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29d70191a60fec166975dc45fedbd47cbf6a5bcd6a7789e352b65182a06aaf210d000ad57cedd4b5a9111dc74c5911f1cf9571b23bde0d7448e43c1cf5436159
  rollbar_token: 56d74b3cc3ac4ce1bd207919c500ec4e
  rsa_private: |
    -----BEGIN RSA PRIVATE KEY-----
    MIICXAIBAAKBgQCelKQN5FyHRvmtOzP+Ft2aVu9RoJMHnc9SFtOJ2PbhJEAyqhgA
    V+ab4rvL+rhCkybs5nkZSpnxbBGHnOiBKfSsquBHQR6zCz78XpdMkRcROJyn+ZVA
    gwF0GvQksyM/v8JVzlsI9gCf0HDKrpS2j0n2eD9Gjle0/p+a4yXtZU8r5wIDAQAB
    AoGADc6PQg5h5/1L+8Mt0a+X97od+BNs+brJtDH8lQHo7M1FMaQRluYQU/43r5jS
    tiktuG6QmJ0gLh7kn9QPgj9u5/6X6XckpXXZhPQp3hbvAPjn90J5gGVGHRWyvCul
    NdxVwpZa/o03DJtGm1VHPGGjiswlOSMAV9i+9AAE12PpZOECQQDOqYWWeqtt2HlL
    q7CUSoFkfwzcer9cvJiQkhW3x08BxTDQ1jh7D/yn3RqIvR+ZdcM0nQYjAuPa67cd
    TjZ6x2bPAkEAxHCKQXjXrT0cQebul827h/uAQ745D7lPqOY8oy6mG2o3BVgWjNBu
    ptzKcaN4xY66xUr5+Jb/7gIZ1iLBYXovaQJBAL5nR5It8RXidVa3l5f40SAjQlk8
    qmSpyjKgtWu+MNejs2clh6IyR4jtWE4VWTDNZA1sgsPtHLuNowdYES+r2dcCQCh2
    9kPeXK8282cv5t4mZwbv69AIk0CF777fDoaeyWDEVGkpaBvBo8mDmcAm6G3ppNeX
    Rj7K/BVPIXtW1Xb68GECQFQdaqutcrmTjUW701BXEjNl/AGbcGhVjE6C8gQGACtV
    fROnPpHP6TLP/kHrjI4BcG9sUKlMgwqwt3ArhFUwxxA=
    -----END RSA PRIVATE KEY-----
test:
  secret_key_base: 130f09c0aaf6f67c6d7b6baa1e1179ce1f9328b7d65790619b28ad98cc7e4acf00d5d530101c1a40da695294f5a804e6b9ada8a68f410ab3ece2bb15334d7051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
